"""empty message

Revision ID: 3a51b2e20505
Revises: d489b4535ed0
Create Date: 2017-11-09 22:53:17.766188

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3a51b2e20505'
down_revision = 'd489b4535ed0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filemap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=128), nullable=False),
    sa.Column('auth_key', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column(u'appinfo', 'app_executable_file',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column(u'appinfo', 'app_name',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column(u'appinfo', 'is_encrypted',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'appinfo', 'is_encrypted',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column(u'appinfo', 'app_name',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column(u'appinfo', 'app_executable_file',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.drop_table('filemap')
    # ### end Alembic commands ###
