"""empty message

Revision ID: 41e45ddf136c
Revises: 3a51b2e20505
Create Date: 2017-11-10 00:12:20.519136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41e45ddf136c'
down_revision = '3a51b2e20505'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filemap', sa.Column('file_orig_name', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filemap', 'file_orig_name')
    # ### end Alembic commands ###
