"""empty message

Revision ID: d489b4535ed0
Revises: f9d7c180b074
Create Date: 2017-11-07 23:52:05.560971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd489b4535ed0'
down_revision = 'f9d7c180b074'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_plantform', sa.String(length=30), nullable=False),
    sa.Column('task_type', sa.String(length=30), nullable=False),
    sa.Column('task_uploads_url', sa.String(length=128), nullable=False),
    sa.Column('task_create_time', sa.DateTime(), nullable=False),
    sa.Column('task_status', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=128), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_create_time', sa.DateTime(), nullable=False),
    sa.Column('file_md5', sa.String(length=60), nullable=False),
    sa.Column('file_sha256', sa.String(length=60), nullable=False),
    sa.Column('app_name', sa.String(length=30), nullable=False),
    sa.Column('app_executable_file', sa.String(length=30), nullable=False),
    sa.Column('app_packid', sa.String(length=30), nullable=True),
    sa.Column('app_miniosversion', sa.String(length=30), nullable=True),
    sa.Column('is_encrypted', sa.Integer(), nullable=False),
    sa.Column('file_hierachy', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appinfo')
    op.drop_table('tasks')
    # ### end Alembic commands ###
