"""empty message

Revision ID: edd4311c8d34
Revises: f133eb098e36
Create Date: 2017-11-14 22:53:49.854822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edd4311c8d34'
down_revision = 'f133eb098e36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filemap', sa.Column('filemap_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filemap', 'filemap_id')
    # ### end Alembic commands ###
