"""empty message

Revision ID: f3ed64cd0b63
Revises: edd4311c8d34
Create Date: 2017-11-14 22:56:58.127789

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f3ed64cd0b63'
down_revision = 'edd4311c8d34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filemap', 'filemap_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filemap', sa.Column('filemap_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
